# Generated by Django 6.0.1 on 2026-01-22 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_vision_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='target_month',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='VisionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3)),
                ('vision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vision')),
            ],
        ),
    ]
