# Generated by Django 6.0.1 on 2026-01-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_vision_target_month_visiontask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiontask',
            name='month',
            field=models.CharField(max_length=20),
        ),
    ]
