# Generated by Django 6.0.1 on 2026-01-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_todoitem_user_vision_user_visiontask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vision',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='main_app/static/uploads/'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='target_month',
            field=models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3),
        ),
    ]
