# Generated by Django 6.0.1 on 2026-01-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_vision_description_alter_vision_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visiontask',
            options={'ordering': ['month']},
        ),
    ]
