# Generated by Django 6.0.1 on 2026-01-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_visiontask_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
