# Generated by Django 6.0.1 on 2026-02-01 13:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_todoitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.visiontask'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
