# Generated by Django 6.0.1 on 2026-02-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_todoitem_task_alter_todoitem_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visiontask',
            options={},
        ),
    ]
