# Generated by Django 5.0.1 on 2026-02-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_todoitem_id_alter_vision_id_and_more'),
    ]

    operations = [
    ]
