# Generated by Django 5.0.1 on 2026-02-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_fix_model_changes'),
    ]

    operations = [
    ]
